version: '3'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        hostname: prometheus
        restart: on-failure
        user: '0'
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus/data'
            - '--storage.tsdb.retention=90d'
            - '--web.enable-lifecycle'
        volumes:
            - ./etc/prometheus:/etc/prometheus
            - ./data/prometheus/data:/prometheus/data
        depends_on:
            - cadvisor
        ports:
            - "9090:9090"
        networks:
            - monitor

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: on-failure
        volumes:
            - ./etc/alertmanager:/etc/alertmanager
        ports:
            - "9093:9093"
        networks:
            - monitor

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        restart: on-failure
        user: '0'
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - "3000:3000"
        networks:
            - monitor

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        hostname: node-exporter
        restart: on-failure
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
            - '--collector.textfile.directory=/node_exporter/prom'
        volumes:
            - /proc:/host/proc
            - /sys:/host/sys
            - ./data/node_exporter/prom:/node_exporter/prom
        ports:
            - "9100:9100"
        networks:
            - monitor

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        hostname: cadvisor
        restart: on-failure
        volumes:
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - "8080:8080"
        networks:
            - monitor

networks:
    monitor:
        driver: bridge